apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-merge-test
  namespace: action-merge-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-mem-load-group
  template:
    metadata:
      labels:
        app: cpu-mem-load-group
    spec:
      containers:
        - name: cpu-mem-load
          image: beekman9527/cpumemload:latest
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 130Mi
              cpu: 100m
          env:
            - name: RUN_TYPE
              value: "memory"
            - name: MEMORY_NUM
              value: "1"
        - name: cpu-mem-load-test-sidecar
          image: beekman9527/cpumemload:latest
          resources:
           limits:
             memory: 200Mi
           requests:
             memory: 130Mi
          env:
            - name: RUN_TYPE
              value: "memory"
            - name: MEMORY_NUM
              value: "1"
